import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import HeaderLayout from "~/components/HeaderLayout";

import { api } from "~/utils/api";
import Timeline from "~/components/Timeline";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-5 flex justify-center"></div>
      <Timeline />
    </>
  );
};

export default Home;
